export * from './client';
export * as authApi from './auth';
export * as usersApi from './users';
export * as projectsApi from './projects';
export * as uploadApi from './upload';
export * as notificationsApi from './notifications';
export * as coordinatorApi from './coordinator';
export * as adviserApi from './adviser';
export * as defensesApi from './defenses';
export * as transcriptionsApi from './transcriptions';
export * as recordingsApi from './recordings';
export * as paperVersionsApi from './paperVersions';
export * as paperReviewsApi from './paperReviews';
